language: elm
elm: latest-0.19.1
elm-test: 0.19.1
elm-format: 0.8.3
node_js: "12"

before_script:
  - elm-format src/ --yes
  - elm-format tests/ --yes

cache:
  directories: # so subsequent builds run faster
    - $HOME/.npm

notifications:
  email: false
