language: elm
elm: 0.19.0
elm-test: 0.19.0-rev3
elm-format: 0.8.0
node_js: "9"

cache:
  directories: # so subsequent builds run faster
    - $HOME/.npm

script:
  - make clean
  - make

notifications:
  email: false
